### ISSUE TITLE
Piece insertion issue

### ISSUE THREAD

**Issue by Henotis** [ddesir/connect-4#9]
Putting X in drops it to the bottom but it pushes everything in the array up, so putting X into a column:
X
O
O
would make it:
X
O
O
X

we need a way for the pieces to replace the next " " in any column and not just anywhere.

**Comment by yauhofung** [comment]
That is why I removed all the empty spaces from the board in an earlier commit. The array's `push()` method does not recognize whitespace as an empty slot.

**Comment by yauhofung** [comment]
Henry, I like the approach in your `choose(x, y)` function, but we shouldn't add to the board's front. We should utilize the array's `push()` method to add to the board.

**Comment by yauhofung** [comment]
Issue resolved: Insertion implemented using array's `push()` method.
